name: iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Uninstall Maven 3.9
        run: |
          brew uninstall maven

      - name: Download Maven 3.8.8
        run: curl -O https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz

      - name: Extract Maven 3.8.8
        run: tar -xzf apache-maven-3.8.8-bin.tar.gz

      - name: Verify Maven 3.8.8 installation
        run: /usr/local/apache-maven-3.8.8/mvn -v

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Gluon Build
        run: /usr/local/apache-maven-3.8.8/mvn -Pios gluonfx:build gluonfx:package

      - name: Make staging directory
        run: mkdir staging

      - name: Copy packages to staging
        run: cp -r target/gluonfx/ios/gvm/BeeAware.* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging